### ISSUE TITLE
invalid install.xml file

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#10]
the install.xml file is not valid and appears to have been handwritten. Please use the core Moodle xmldb editor to fix this.

**Comment by braincert** [comment]
This is now fixed. Thanks.

**Comment by danmarsden** [comment]
it doesn't look like you have fixed this. Please use the xmldb editor to load the install.xml file, make a change and then use the xmldb editor built in tools to save the file. There are still a number of issues with this file.

**Comment by arvinddubey** [comment]
We have edited install.xml file using moodle xmldb editor. Thanks.

**Comment by developerck** [comment]
cross validated.  it is loading working.
