### ISSUE TITLE
please use Moodle curl class instead of PHP curl functions

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#12]
Many Moodle sites will sit behind a proxy and Moodle provides a centrally managed curl class for managing curl requests - please use the core moodle curl class instead of using php curl functions.

**Comment by arvinddubey** [comment]
Plugin has been rectified and now it is using native Moodle curl class to consume external api calls.
Thanks.

**Comment by danmarsden** [comment]
can you please check these old issues and close the ones you think have since been resolved?  - thanks!

**Comment by developerck** [comment]
cross-validated. moodle default curl class is being utilized. so closing this ticket.
