### ISSUE TITLE
classes need to use frankenstyle naming or namespacing.

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#13]
classes like "adddiscount_form" need to follow the naming convention and use a frankenstlye prefix eg "braincert_adddiscount_form" or the better option is to namespace them within:
namespace mod_braincert
more info on the naming rules is here:
https://docs.moodle.org/dev/Coding_style#Namespaces

**Comment by developerck** [comment]
module name space has been added. So marking this close.
