### ISSUE TITLE
Missing capability checks.

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#14]
Good to see better use of require_login($course) but it looks like many pages that should only be usable/accessible by teaching staff are not making any capability checks.

even the student ones should be checking the braincert_view capability defined in your db/access.php but you should probably create a new capability to protect the pages that should only be used by teaching staff too.

**Comment by danmarsden** [comment]
we have a good summary of security guidelines here that is worth a read:
https://docs.moodle.org/dev/Security#Summary_of_the_guidelines

**Comment by developerck** [comment]
Thanks for informing this. requried capabilities are in place.
