### ISSUE TITLE
functions need to follow frankenstlye naming rules

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#15]
function names need to start with "mod_braincert" - although activity module plugins are allowed to exclude the first part of the frankenstly name and just use "braincert"
for example task_add_special_params is incorrect and should be:
mod_braincert_task_add_special_params or
braincert_task_add_special_params or

see here for more info on the rules:
https://docs.moodle.org/dev/Coding_style#Functions_and_Methods

**Comment by developerck** [comment]
all function name has been changed as per the convention.
