### ISSUE TITLE
settings mod_braincert_apikey mod_braincert_baseurl stored in wrong place.

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#16]
plugin settings are supposed to use the config_plugins table and retrieved using api calls to get_config rather than being stored in the main $CFG global.
a good example to look at is assign:
https://github.com/moodle/moodle/blob/master/mod/assign/settings.php#L45

you can see the name of the setting is not assign_feedback_plugin_for_gradebook but assign/feedback_plugin_for_gradebook - which puts it in the config_plugins table with the plugin name "assign"

**Comment by developerck** [comment]
This has beem modified as needed.
