### ISSUE TITLE
incorrect privacy api class.

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#18]
The privacy class you have implemented is the null provider, but your braincert_class_purchase table contains user data that should be covered in your privacy api functions.

You also need to indicate that you pass information to an external location as per:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

Privacy API support is not usually a blocker for approval in the plugins db, but if you don't implement this for your first version I'd prefer you to delete the invalid privacy class as it is not telling the truth to Moodle's Privacy Officer.

**Comment by developerck** [comment]
Thanks @danmarsden . For the time being , as you have said, i have remvoed the incorrect defination of privacy.
We are working on that part regrading field and information. meanwhile we would like to push this. We will update this with privacy version soon.  this is the reason , I am keeping this open.

**Comment by developerck** [comment]
privacy api has been implemented.
