### ISSUE TITLE
styles.css needs to be more specific

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#19]
the styles.css file in all plugins are combined into a single css file for better caching. This also means that your styles need to be extremely specific - classes like ".dropdown-content" are too generic and could incorrectly get applied to things outside the braincert plugin.

there are a few different ways to do this - one of the easiest is to use the automatically added class ".path-mod-braincert " to the start of all your css tags in the styles.css file - take a look at some of the other core plugin styles.css files for examples.

**Comment by developerck** [comment]
context class has been added.
