### ISSUE TITLE
direct access to raw $_POST/$_GET/$_REQUEST is not allowed

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#2]
Please replace these with optional/required_param functions with appropriate sanitisation.

**Comment by braincert** [comment]
Fixed.

**Comment by danmarsden** [comment]
this does look better, although I see a lot of use of PARAM_RAW in a lot of places that should have other cleaning methods (PARAM_RAW is just the same as raw $_GET)

**Comment by arvinddubey** [comment]
Corrected it and removed direct usages of PARAM_RAW and $_GET. thanks.

**Comment by developerck** [comment]
This has been fixed . So marking this issue close.
