### ISSUE TITLE
incorrect method used for defining "persona" - hard-coded role shortnames

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#22]
You should be using capabilities to check if the user is a teacher/student - many organisations will delete the student/teacher/editingteacher roles so your code will not work.

Also - watch out for our naming conventions for constants - "PERSONA_ADMIN" is incorrect. see:
https://docs.moodle.org/dev/Coding_style#Constants

**Comment by developerck** [comment]
capability has been added instead of role.
