### ISSUE TITLE
Generic error messages in Moodle 3.8

### ISSUE THREAD

**Issue by pkExec** [braincert/moodle-mod_braincert#24]
Trying to add a Braincert activity in Moodle 3.8, generates just unhelpful messages:

```
Error code: invalidfunction
Stack trace:
    line 494 of /lib/setuplib.php: moodle_exception thrown
    line 142 of /course/modlib.php: call to print_error()
    line 155 of /course/modedit.php: call to add_moduleinfo()
```
If I add the following line after line 140 in /course/modlib.php, (which I don't want to do, it's a moodle core hack) I can see the actual error messages:
`echo $returnfromfunc;`

A sample error message after enabling the above line: 
`<div class="alert">Your 'Free' plan supports limited datacenter selection. <a href='https://www.braincert.org/membership/premium/vc-api' target='_blank'>Upgrade</a> today.</div>`

**Comment by developerck** [comment]
addeed the activity, tried in 3.8.2,  3.9 as well, didn't find. The message is genuine and it shows without adding the hack if condition fails.
