### ISSUE TITLE
This plugin can not be translated in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [braincert/moodle-mod_braincert#26]
This plugin can not be translated in AMOS.
The cause seems to be string concatenation (which is not allowed), e.g.
$string['change_language_help'] = 'Allow attendees to change virtual classroom interface to '
        . 'the language of their choice. The default language is english.';
        
        Please fix string concatenation so that we can translate this plugin in AMOS.

**Comment by braincert** [comment]
This issue has been fixed. You can download latest code and try it out.

**Comment by germanvaleroelizondo** [comment]
You must update the code hosted at the Moodle plugins database at https://moodle.org/plugins/mod_braincert

ONLY after you upload your code there will the AMOS strings be available for translation (and only if there are no more coding errors).

**Comment by braincert** [comment]
Hi there.. Plugin version 1.5 uploaded to Moodle plugin database. Thank you.

**Comment by germanvaleroelizondo** [comment]
Thanks for fixing the string concatenation.
Sadly, the plugin can not be translated because it is in the "Other" category in the Moodle plugins database. 
See https://docs.moodle.org/dev/Translating_plugins#Plugins_in_the_Other_category
