### ISSUE TITLE
moodle.org code precheck failures

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#5]
you should take a look at the precheck failures shown at the top of this page:
https://moodle.org/plugins/pluginversion.php?id=17725
(you will need to be logged in to moodle.org with the braincert account to view this page as the plugin has not been approved yet.)

In particular the phplint failure concerns me...

**Comment by arvinddubey** [comment]
Used Eslint and Stylelint to scan js and css files. Also we are using moodlerooms/moodle-plugin-ci scanner script to make sure that plugin should be as per the Moodle standard.

**Comment by developerck** [comment]
code is scanned as per moodle ci scanner . so closing this.
