### ISSUE TITLE
classes should be implemented in a classes folder within the plugin

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#7]
This class should be in it's own file within the classes folder in your plugin:
https://github.com/braincert/Moodle-HTML5-Virtual-Classroom-Plugin/blob/master/adddiscount.php#L72

Please check for any other classes embedded in-line in your other files and move them into the classes folder.

**Comment by braincert** [comment]
This is now fixed. Thanks.

**Comment by developerck** [comment]
this has been fixed. so closing this.
