### ISSUE TITLE
Missing Privacy API class

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#8]
Moodle now implements a new privacy api - it would be nice if you could implement this in your plugin. Sites that use continuous integration processes will not be able to use your plugin as Moodle now includes unit tests to check that all installed plugins contain appropriate privacy classes.
more information on the privacy api is here:
https://docs.moodle.org/dev/Privacy_API

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by braincert** [comment]
This is now fixed. Thanks.

**Comment by danmarsden** [comment]
I presume that comment was accidental. You have not yet implemented the privacy api classes.

**Comment by arvinddubey** [comment]
Privacy API class has been added in plugin.

**Comment by developerck** [comment]
this has been added.
